from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from .state import ConstraintSet, PartObservation, PartState


def load_json(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Expected JSON object: {path}")
    return data


def infer_category(part_id: str, fallback: str = "guide") -> str:
    if "weapon" in part_id:
        return "weapon"
    if "boot" in part_id:
        return "costume"
    if part_id.startswith("leg_") or part_id == "legs":
        return "body"
    if "hair" in part_id or "bangs" in part_id:
        return "hair"
    if "cape" in part_id or "skirt" in part_id:
        return "cloth"
    if "face" in part_id:
        return "face"
    return fallback


def infer_generator(part_id: str, fallback: str | None = None) -> str | None:
    if "weapon" in part_id:
        return fallback or "weapon_panel"
    if "boot" in part_id:
        return fallback or "boot_proxy"
    if part_id.startswith("leg_"):
        return fallback or "leg_proxy"
    return fallback


def normalize_part_states(spec: dict[str, Any], report: dict[str, Any]) -> list[PartState]:
    main_visible = set(spec.get("v8_visibility_split", {}).get("main_visible_meshes", []))
    debug_only = set(spec.get("v8_visibility_split", {}).get("debug_only_guides", []))
    cage_names = set(report.get("cage_glb_roundtrip", {}).get("mesh_names", []))
    main_names = set(report.get("glb_roundtrip", {}).get("mesh_names", []))

    report_parts = {
        part.get("id"): part
        for part in report.get("parts", [])
        if isinstance(part, dict) and isinstance(part.get("id"), str)
    }
    states: dict[str, PartState] = {}

    for part in spec.get("parts", []):
        if not isinstance(part, dict) or not isinstance(part.get("id"), str):
            continue
        part_id = part["id"]
        rich = report_parts.get(part_id, {})
        states[part_id] = PartState(
            id=part_id,
            category=part.get("category") or rich.get("category") or infer_category(part_id),
            parent=rich.get("parent"),
            generator=part.get("generator") or rich.get("generator"),
            depth=part.get("depth") if part.get("depth") is not None else rich.get("depth"),
            thickness=rich.get("thickness"),
            curvature=rich.get("curvature"),
            bbox=part.get("mask_bbox") or rich.get("bbox"),
            texture=part.get("texture") or rich.get("texture"),
            card_count=rich.get("card_count"),
            visible_in_beauty=part_id in main_names,
            visible_in_cage=part_id in cage_names,
            debug_only=part_id in debug_only,
            source="spec.parts+validation_report.parts",
            known_limits=[part["dcc_note"]] if isinstance(part.get("dcc_note"), str) else [],
        )

    for part_id in sorted(main_visible | debug_only | main_names | cage_names):
        if part_id in states:
            states[part_id].visible_in_beauty = part_id in main_names
            states[part_id].visible_in_cage = part_id in cage_names
            states[part_id].debug_only = part_id in debug_only
            continue
        states[part_id] = PartState(
            id=part_id,
            category=infer_category(part_id),
            generator=infer_generator(part_id),
            visible_in_beauty=part_id in main_names,
            visible_in_cage=part_id in cage_names,
            debug_only=part_id in debug_only,
            source="v8_visibility_split+roundtrip",
            known_limits=["generated by v7/v8 cleanup, not present in original spec parts"],
        )

    return [states[key] for key in sorted(states)]


def build_observations(spec: dict[str, Any], report: dict[str, Any], states: list[PartState]) -> list[PartObservation]:
    observations: list[PartObservation] = []
    side_back = spec.get("side_back_constraints") or report.get("side_back_constraints") or {}
    policy = str(side_back.get("policy", ""))
    side_confidence = 0.45 if "not locked" in policy else 0.35
    back_confidence = 0.50 if "not locked" in policy else 0.35

    report_parts = {
        part.get("id"): part
        for part in report.get("parts", [])
        if isinstance(part, dict) and isinstance(part.get("id"), str)
    }
    main_names = set(report.get("glb_roundtrip", {}).get("mesh_names", []))
    cage_names = set(report.get("cage_glb_roundtrip", {}).get("mesh_names", []))
    warnings = report.get("quality", {}).get("warnings", [])

    for state in states:
        rich = report_parts.get(state.id, {})
        observations.append(
            PartObservation(
                part_id=state.id,
                source="front",
                confidence=1.0,
                bbox=state.bbox or rich.get("bbox"),
                roundtrip_present=state.id in main_names,
            )
        )
        observations.append(
            PartObservation(
                part_id=state.id,
                source="validation",
                confidence=0.85,
                roundtrip_present=state.id in main_names or state.id in cage_names,
                warnings=[warning for warning in warnings if isinstance(warning, str)],
            )
        )
        observations.append(
            PartObservation(
                part_id=state.id,
                source="side",
                confidence=side_confidence,
                coverage=side_back.get("side", {}).get("alpha_coverage"),
                warnings=["side/back are soft inferred constraints"],
            )
        )
        observations.append(
            PartObservation(
                part_id=state.id,
                source="back",
                confidence=back_confidence,
                coverage=side_back.get("back", {}).get("alpha_coverage"),
                warnings=["side/back are soft inferred constraints"],
            )
        )
    return observations


def detect_constraints(spec: dict[str, Any]) -> ConstraintSet:
    policy = str(spec.get("side_back_constraints", {}).get("policy", "")).lower()
    return ConstraintSet(
        side_back_are_soft="not locked" in policy or "soft" in policy or bool(policy),
    )

