from __future__ import annotations

import json
from pathlib import Path

from .state import FilterDecision, FilterReport


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def build_candidate_spec(report: FilterReport) -> dict:
    return {
        "route": "semantic_layer_v9_candidate_spec_only",
        "source_route": report.input_route,
        "formula": report.formula,
        "boundary": "Candidate planning spec only. No GLB/FBX/OBJ is generated by semantic_state_filter_v0.",
        "constraints": report.constraints.to_dict(),
        "global_decisions": report.global_decisions,
        "parts": [state.to_dict() for state in report.part_states],
        "decisions": [decision.to_dict() for decision in report.part_decisions],
        "proposed_actuator_order": [
            "weapon_hardsurface_ortho",
            "boot_hardsurface_ortho",
            "leg_quad_loop_retopo_proxy",
            "authored_hair_ribbons",
            "cloth_seam_surface",
        ],
    }


def decision_markdown(decisions: list[FilterDecision]) -> str:
    rows = [
        "# Semantic State Filter v0 Decisions",
        "",
        "This is a read-only planning pass. It does not modify v8 and does not generate new mesh exports.",
        "",
        "| Part | Decision | Proposed generator | Confidence | Reason |",
        "|---|---|---|---:|---|",
    ]
    for decision in decisions:
        reason = decision.reason.replace("|", "\\|")
        rows.append(
            f"| `{decision.part_id}` | `{decision.decision}` | "
            f"`{decision.proposed_generator or ''}` | {decision.confidence:.2f} | {reason} |"
        )
    rows.append("")
    rows.append("## Required Guarantees")
    rows.append("")
    rows.append("- v8 remains untouched.")
    rows.append("- Debug-only guides stay out of the beauty GLB.")
    rows.append("- Side/back references remain soft constraints.")
    rows.append("- Current beauty meshes stay until replacements are validated.")
    return "\n".join(rows) + "\n"

